const fs = require('fs');
const path = require('path');
const os = require('os');

/**
 * Maker-Checker module.
 * The "maker" proposes a staleness report as markdown;
 * the "checker" (human) must review and approve before any action is taken.
 * This module never auto-merges or auto-edits README files.
 */
class MakerChecker {
  constructor(reportsDir = path.join(process.cwd(), 'reports')) {
    this.reportsDir = reportsDir;
    if (!fs.existsSync(this.reportsDir)) {
      fs.mkdirSync(this.reportsDir, { recursive: true });
    }
  }

  /**
   * Propose a staleness report markdown string given a stale list and date.
   * Does NOT write to disk or create GitHub issues.
   * @param {Array<Object>} staleList - List from skill.checkStaleness()
   * @param {string} reportDate - ISO date string for the report title
   * @returns {string} Markdown report text
   */
  generateReport(staleList, reportDate) {
    const dateObj = new Date(reportDate);
    const formattedDate = dateObj.toISOString().split('T')[0];

    let markdown = `# Docs Freshness Report - ${formattedDate}\n\n`;

    markdown += `*Generated on ${new Date().toISOString().split('T')[0]}*\n\n`;

    if (staleList.length === 0) {
      markdown += `## No stale READMEs found\n\n`;
      markdown += `All project READMEs have been updated within the last ${30} days.`;
    } else {
      markdown += `## Stale READMEs Found (${staleList.length} projects)\n\n`;

      markdown += `| Project | Days Old | Last Commit |\n`;
      markdown += `|---------|----------|-------------|\n`;

      for (const entry of staleList) {
        const lastCommit = entry.lastModified
          ? new Date(entry.lastModified).toISOString().split('T')[0]
          : 'unknown';
        markdown += `| ${entry.project} | ${entry.daysOld} | ${lastCommit} |\n`;
      }

      markdown += `\n`;
      markdown += `| | | |\n`;
      markdown += `|---|---|---|\n`;
      markdown += `| Total stale | ${staleList.length} | |\n`;
      markdown += `| Threshold | 30 days | |\n`;
    }

    markdown += `\n---\n\n`;
    markdown += `*This report was auto-generated by the docs-freshness loop.`;
    markdown += ` A human reviewer must approve any action based on these findings.*\n`;

    return markdown;
  }

  /**
   * Write the proposed report to disk for human review.
   * @param {string} markdown - The markdown report text
   * @param {string} filename - Optional filename (defaults to date-based name)
   * @returns {string} The path where the report was written
   */
  writeReport(markdown, filename) {
    let fname;
    if (!filename) {
      const date = new Date().toISOString().split('T')[0];
      fname = `staleness-report-${date}.md`;
    } else {
      fname = filename;
    }
    const filePath = path.join(this.reportsDir, fname);
    fs.writeFileSync(filePath, markdown, 'utf8');
    return filePath;
  }

  /**
   * Read a previously written report from disk.
   * @param {string} filename - Name of the report file (without path)
   * @returns {string|null} The report markdown, or null if not found
   */
  readReport(filename) {
    const filePath = path.join(this.reportsDir, filename);
    if (fs.existsSync(filePath)) {
      return fs.readFileSync(filePath, 'utf8');
    }
    return null;
  }

  /**
   * List all previously generated reports.
   * @returns {Array<Object>} List of {filename, created} entries
   */
  listReports() {
    const files = fs.readdirSync(this.reportsDir).filter(f => f.endsWith('.md'));
    return files.map(f => ({
      filename: f,
      path: path.join(this.reportsDir, f),
    }));
  }
}

module.exports = { MakerChecker };