$branch = "claude/summary"

# Create and checkout new branch
try {
    git checkout -b "$branch"
} catch {
    git checkout "$branch" 2>$null
    if ($LASTERROR) {
        # Branch may not exist; create it
        git checkout -b "$branch"
    }
}

# Create a small summary file
$summary = "Summary of proposed changes:
- This is a one-line summary generated by Routine A
- Change adds a reviewable draft in claude/summary branch
- No automatic pushes or merges"

$filePath = "summary.txt"
Set-Content -Path "$filePath" -Value $summary -Encoding UTF8

# Stage the file
git add "$filePath"

# Show what was produced
Write-Output "=== Routine A output ==="
Write-Output "Branch: $branch"
Write-Output ""
Write-Output " staged files:"
git diff --staged --stat
Write-Output ""
Write-Output "Uncommitted changes in working directory:"
git diff --stat